### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by mia-federicobortot** [mia-platform/design-system#116]
https://github.com/mia-platform/design-system/blob/71579f344b5036bbcd222d01ed5592f0379b7cd8/src/themes/schema/typography.ts#L31C70-L31C70

Current link is pointing to "font size" section; 
correct link could be: https://developer.mozilla.org/en-US/docs/Web/CSS/font-style

**Comment by Giogia** [comment]
Fixed in #118
