### ISSUE TITLE
Add Breadcrumb component

### ISSUE THREAD

**Issue by fedepini** [mia-platform/design-system#463]
## The feature or bug you are proposing
Creation of a `Breadcrumb` component to ease navigation.

## The description of the bug or the rationale of your proposal
It would be nice to introduce an UI component to allow users to navigate between sections. This component should not be necessarily associated with the `react-dom-router` or represent a routing, but it could be also used to navigate inside a sub-section (e.g. inside a modal or a drawer).

The expected `Breadcrumb` component should have as input only an `items` property, which will contain a list of breadcrumb items to be displayed. The component should have the following props:

    type BreadcrumbProps = {
        items: BreadcrumbItemType[]
    }

Each specific item should be of type `BreadcrumbItemType`, structured this way

    type BreadcrumbItemType = {
        icon?: ReactNode
        key?: string
        label?: ReactNode
        menu?: BreadcrumbItemMenu
        onClick?: (event: React.MouseEvent<Element, MouseEvent>) => void
    }

If at least one of the `icon`, `label` or `menu` props are not undefined and contain a valid value, the component should display the associated value. If unspecified, the `key` property is set at the `items` index. If more than one item is present, the items should be displayed and divided by a fixed separator (`>`). As visible inside the type, each item contains an `onClick` prop to allow users to define the expected behavior to be executed when clicking.

If the item contains a valid `menu` value, the component should display an element containing a dropdown icon. If not specified otherwise, clicking this icon will open a dropdown, which will display the menu elements, if present, and a search bar, if specified.

The menu type should look like this:

    type BreadcrumbItemMenu = {
        activeKey?: string
        items?: BreadcrumbItemMenuItem[]
        onDropdownVisibleChange?: (open: boolean) => void
        onSearch?: OnSearch
        open?: boolean
        searchAllowClear?: boolean
        searchPlaceholder?: string
        showSearch?: boolean
    }

The `showSearch`, `searchPlaceholder`, `searchAllowClear` and `onSearch` props will give freedom to the user to specify if and how the search function should work. The `open` and `onDropdownVisibleChange` props allow to specify the dropdown behavior. If not specified, the internal state will be used to open and close the dropdown when clicking on the dropdown icon. The `activeKey` prop will be used to specify if one of the sub-items has already been selected. If so, its `label` will be displayed as the label of the parent `BreadcrumbItem` component, otherwise, the parent `label` will be displayed, if present. The `items` prop should contain a list of element with the following structure:

    type BreadcrumbItemMenuItem = {
        icon?: ReactNode
        key?: string
        onClick?: (event: React.MouseEvent<Element, MouseEvent>) => void
        label: string
    }

As for the previous type, if the key is unspecified, the `items` index will be used as key. Here as well the `onClick` property of each sub-item is left to be handled by a custom function.

**Comment by epessina** [comment]
LGTM
