### ISSUE TITLE
Color icon for Button component even on hover

### ISSUE THREAD

**Issue by valesceva** [mia-platform/design-system#521]
## The feature or bug you are proposing
Add color to icon added to icon props of Button like the text, it should work even if i pass the icon component

## A snippet of code for replicating the issue or showing the proposal usage if applicable
`<Button hierarchy='neutral' icon={<Icon name='FiDownload' size={16} />} type={'outlined'} />`

**Comment by fredmaggiowski** [comment]
If you need the Icon to change color during button interactions, like hovering etc, the best approach is to use `color="currentColor"`
