### ISSUE TITLE
Modal stories should show the component props

### ISSUE THREAD

**Issue by GiovannaMonti** [mia-platform/design-system#533]
## The description of the bug or the rationale of your proposal

Right now, the Show Code tab in Modal stories displays code snippets like the following one:

```
{
  args: meta.args,
  decorators: [(_, {
    args
  }) => <WithOpenButton {...args} />]
}
```

The actual props are hidden because the story is rendering a wrapper component (used to show the Open button and the Modal itself). This way, the stories are pretty useless.

The expected outcome of this issue is that Modal stories only include the Modal component and its props.

**Comment by fredmaggiowski** [comment]
This duplicates #503
