### ISSUE TITLE
The injected theme css variables are not available in the modal

### ISSUE THREAD

**Issue by MIA-Deltat1995** [mia-platform/design-system#553]
## The feature or bug you are proposing
The CSS variables inserted by the ThemeProvider are not available in the Modal content and in any HTML element that is external to the div element of the ThemeProvider

## A snippet of code for replicating the issue or showing the proposal usage if applicable
Using the browser ispector on the modal content of the storybook, it is clear that the css variables are not inherited and instead there are on the button 'Open Modal' used to open the modal.

**Comment by Danielecina** [comment]
All feedback Antd components are spawned to the default tag <body />. It is possible to change this default globally. In case it isn't possible we can think of using portals or something to push all of these elements to the ThemeProvider node
