### ISSUE TITLE
Dropdown: Can't control onClick on menu items

### ISSUE THREAD

**Issue by valesceva** [mia-platform/design-system#743]
When in a Dropdown is present a menu item, I can't use stopPropagation() on that click event. 
I used it inside a table with onRow click and it triggers that handle.

https://github.com/user-attachments/assets/d8404e20-a67a-437c-b85a-dfc66f00c98f

My code:
```typescript
// Definizione degli elementi del dropdown
const items: DropdownItem[] = [
  {
    label: <FormattedMessage data={'edit.swi'} />,
    id: 'edit',
    icon: <Icon component={PiPencilSimpleLine} size={16} />
  },
  {
    id: 'download',
    label: <FormattedMessage data='download.activity.history' />,
    icon: <Icon component={PiDownloadSimple} size={16} />,
    children: [
      {
        label: <FormattedMessage data={'pdf'} />,
        id: 'pdf',
        icon: <Icon component={PiFilePdf} size={16} />
      },
      {
        label: <FormattedMessage data='json' />,
        id: 'json',
        icon: <Icon component={PiFileJs} size={16} />
      }
    ]
  },
  {
    label: <FormattedMessage data={'delete.item'} />,
    id: 'delete',
    icon: <Icon color='currentcolor' component={PiTrash} size={16} />,
    danger: true
  }
];

// Gestione del click sul dropdown
const onClickDropdown = (event: DropdownClickEvent): void => {
  event.domEvent.stopPropagation();
  switch (event.id) {
    ...
  }
};

// Uso del Dropdown
<Dropdown items={items} onClick={onClickDropdown}>
  <Button />
</Dropdown>;

**Comment by valesceva** [comment]
**Workaround**:
If I put the Dropdown inside an HTMLElement with ```onCLick = (event) => event.stopPropagation()``` fix the problem.

**Comment by fredmaggiowski** [comment]
Hi @valesceva, the [DropdownClickEvent](https://github.com/mia-platform/design-system/blob/main/src/components/Dropdown/props.ts#L118) provides you the `domEvent` field, holding the original DOM Event. You should be able to invoke `domEvemtn.stopPropagation()` 🤔

**Comment by valesceva** [comment]
> Hi @valesceva, the [DropdownClickEvent](https://github.com/mia-platform/design-system/blob/main/src/components/Dropdown/props.ts#L118) provides you the `domEvent` field, holding the original DOM Event. You should be able to invoke `domEvemtn.stopPropagation()` 🤔
> 
> I see that you are doing so in the snipped provided, but I guess it is not working properly, right? can you provide the value you see for the domEvent?
> 
> I've put up a branch (see PR #745) with a story that should replicate your issue, can you verify and confirm the behaviour is the same? It seems to me that the event is properly stopped on the dropdown item list click

Hi @fredmaggiowski, I already apply the domEvent.stopPropagation() but it doesn't work when clicking on a menu item

**Comment by fredmaggiowski** [comment]
I'm glad it is resolved
